### ISSUE TITLE
Bug in STELLout

### ISSUE THREAD

**Issue by ejpaul** [zhucaoxiang/CoilPy#1]
Hi,

I found that I had to delete lines 210-211 in STELLout in order to read the output without getting the error

index 4 is out of bounds for axis 2 with size 4

**Comment by zhucaoxiang** [comment]
@ejpaul Are you saying the following lines?
```python
                self[item+'_m'] = np.array(self[item][:,:,4])
                self[item+'_n'] = np.array(self[item][:,:,5])
```

I haven't checked this part. Usually, I was using the `helicity_full`. It looks the `helicity` option only has four columns.  I have deleted these two lines. Can you please check if it works now?  'pip install -U coilpy' (version 0.2.14)

**Comment by ejpaul** [comment]
This fixed the issue. Thanks!
